version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      # - "8554:8554"     # RTSP
      - "8888:8888"     # HLS
      - "8889:8889"     # WebRTC HTTP
      - "8189:8189/udp" # WebRTC ICE
      - "1935:1935"     # RTMP
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped

  mediamtx2:
    image: bluenviron/mediamtx:latest
    ports:
      # - "8554:8554"     # RTSP
      - "8891:8889"     # WebRTC HTTP instance 2
      - "8190:8190/udp" # WebRTC ICE (different port to avoid conflict)
      # - "8189:8189/udp" # WebRTC ICE
    volumes:
      - ./mediamtx2.yml:/mediamtx.yml
    restart: unless-stopped


  streamer:
    build:
      context: .
      dockerfile: Dockerfile  # or just 'Dockerfile' if that's the name
    depends_on:
      - mediamtx
      - mediamtx2
    command: ffmpeg -re -stream_loop -1 -i /videos/test-video.mp4 -c:v libx264 -g 50 -keyint_min 50 -sc_threshold 0 -bf 0 -pix_fmt yuv420p -c:a libopus -ar 48000 -ac 2 -f rtsp -rtsp_transport tcp rtsp://mediamtx:8554/webrtc_stream -map 0:v -map 0:a -c:v libx264 -g 50 -keyint_min 50 -sc_threshold 0 -bf 0 -pix_fmt yuv420p -c:a libopus -ar 48000 -ac 2 -f rtsp -rtsp_transport tcp rtsp://mediamtx2:8554/webrtc_stream
    volumes:
      - ./test-video.mp4:/videos/test-video.mp4
    restart: unless-stopped